### ISSUE TITLE
Rainbow crashes in MaxQFilter about 1 second after instantiation

### ISSUE THREAD

**Issue by AndrewBelt** [SteveRussell33/Prism#7]
Tested on Linux and Mac, Rack 2.0.4 standalone. After adding Rainbow to the patch, it crashes with this stack trace.
```
0x00007fffcadf0477 in rainbow::MaxQFilter::twopass(rainbow::FilterBank*, int, float**) () from /home/vortico/.Rack2/plugins/Prism/plugin.so
(gdb) bt
#0  0x00007fffcadf0477 in rainbow::MaxQFilter::twopass(rainbow::FilterBank*, int, float**) () at /home/vortico/.Rack2/plugins/Prism/plugin.so
#1  0x00007fffcadee8f2 in rainbow::FilterBank::process_audio_block() () at /home/vortico/.Rack2/plugins/Prism/plugin.so
#2  0x00007fffcade07ec in rainbow::Audio::ChannelProcess1(rainbow::IO&, rack::engine::Input&, rack::engine::Output&, rainbow::FilterBank&) () at /home/vortico/.Rack2/plugins/Prism/plugin.so
#3  0x00007fffcadf3b53 in Rainbow::process(rack::engine::Module::ProcessArgs const&) () at /home/vortico/.Rack2/plugins/Prism/plugin.so
#4  0x00007ffff7749982 in rack::engine::Module::doProcess(rack::engine::Module::ProcessArgs const&) (this=0x5555574646a0, args=...) at src/engine/Module.cpp:345
#5  0x00007ffff77441c1 in rack::engine::Engine_stepWorker (that=<optimized out>, that=<optimized out>, threadId=0) at src/engine/Engine.cpp:376
#6  rack::engine::Engine_stepFrame (that=<optimized out>, that=<optimized out>) at src/engine/Engine.cpp:448
#7  rack::engine::Engine::stepBlock(int) (this=<optimized out>, frames=<optimized out>) at src/engine/Engine.cpp:604
#8  0x00007ffff7744a20 in rack::engine::Engine_fallbackRun(rack::engine::Engine*) (that=0x555555961270) at src/engine/Engine.cpp:1376
#9  0x00007ffff7bcee04 in execute_native_thread_routine () at ./libRack.so
#10 0x00007ffff7022259 in start_thread () at /usr/lib/libpthread.so.0
#11 0x00007ffff71385e3 in clone () at /usr/lib/libc.so.6
```

**Comment by SteveRussell33** [comment]
Hi Andrew,
I take it you're using the build from the library, yes?
Can you build the plugin and test with the debug version? I think I need a bit more detail here.
Thanks.

**Comment by AndrewBelt** [comment]
The above stack trace was from the Library build, but here's a stack trace from another Linux laptop using a build without symbols stripped.
The crash is probabilistic, and it took several seconds and/or instantiations to crash.
```
#0  0x00007ffff45f4c5c in rainbow::MaxQFilter::twopass (this=0x555556590308, fb=0x55555658afb8, channel_num=4, filter_out=0x55555663ac80) at src/Filter.cpp:632
#1  0x00007ffff45f59bc in rainbow::MaxQFilter::filter (filter_out=<optimized out>, channel_num=4, fb=0x55555658afb8, this=0x555556590308) at src/Filter.cpp:492
#2  rainbow::FilterBank::process_audio_block (this=this@entry=0x55555658afb8) at src/FilterBank.cpp:180
#3  0x00007ffff45f5dda in rainbow::Audio::ChannelProcess1 (this=0x555556599020, io=..., input=..., output=..., filterbank=...) at src/Audio.cpp:89
#4  0x00007ffff45fc2c5 in Rainbow::process (this=0x55555658aa70, args=...) at src/Rainbow.cpp:757
#5  0x00007ffff7749922 in rack::engine::Module::doProcess (this=0x55555658aa70, args=...) at src/engine/Module.cpp:345
#6  0x00007ffff7744161 in rack::engine::Engine_stepWorker (that=<optimized out>, that=<optimized out>, threadId=0) at src/engine/Engine.cpp:376
#7  rack::engine::Engine_stepFrame (that=<optimized out>, that=<optimized out>) at src/engine/Engine.cpp:448
#8  rack::engine::Engine::stepBlock (this=<optimized out>, frames=<optimized out>) at src/engine/Engine.cpp:604
#9  0x00007ffff7670fc3 in rack::audio::Device::processBuffer (this=0x55555586bb20, input=0x555555eaaa70, inputStride=2, output=0x555555ea8a60, outputStride=4, frames=512) at src/audio.cpp:45
#10 0x00007ffff769e942 in rack::RtAudioDevice::rtAudioCallback (outputBuffer=0x555555ea8a60, inputBuffer=0x555555eaaa70, nFrames=512, streamTime=<optimized out>, status=<optimized out>, userData=0x55555586bb20) at src/rtaudio.cpp:223
#11 0x00007ffff7b4150d in RtApiAlsa::callbackEvent (this=this@entry=0x5555555eefa0) at /home/vortico/src/vcv/Rack-v2/dep/rtaudio/RtAudio.cpp:8281
#12 0x00007ffff7b41ed5 in alsaCallbackHandler (ptr=0x5555555ef1f8) at /home/vortico/src/vcv/Rack-v2/dep/rtaudio/RtAudio.cpp:8452
#13 0x00007ffff7022259 in start_thread () from /usr/lib/libpthread.so.0
#14 0x00007ffff71385e3 in clone () from /usr/lib/libc.so.6
```

**Comment by AndrewBelt** [comment]
I'd guess that if you add bounds checking to
```cpp
exp_4096[(uint32_t)(qval_b / 1.4f) + 200]
```
you will catch it out of bounds occasionally.

**Comment by SteveRussell33** [comment]
I've made changes that I think should work, although I can't test on Linux or Mac.
Test builds for your review: https://github.com/SteveRussell33/Prism/actions/runs/1653884931

**Comment by SteveRussell33** [comment]
Closing as fixed - test build run no longer valid
